formatter: "md tbl" # this is required

version: ">= 0.16.0, < 1.0.0"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}
  
  ## Usage
  ```hcl
  {{ include "../../../../../terragrunt.example.hcl" }}
  ```

  {{ .Requirements }}

  {{ .Modules }}

  {{ .Providers }}

  {{ .Inputs }}
  
  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
